import { BrowserWindow, session, app } from 'electron';
import path from 'node:path';
import fs from 'node:fs';
import log from 'electron-log/main';

export class YouTubeAuthService {
  private authWindow: BrowserWindow | null = null;
  private cookiesPath: string;

  constructor() {
    this.cookiesPath = path.join(app.getPath('userData'), 'youtube_cookies.txt');
  }

  public async openAuthWindow(): Promise<boolean> {
    if (this.authWindow) {
      this.authWindow.focus();
      return false;
    }

    this.authWindow = new BrowserWindow({
      width: 450,
      height: 700,
      title: 'Đăng nhập YouTube - Melovista',
      autoHideMenuBar: true,
      webPreferences: {
        nodeIntegration: false,
        contextIsolation: true,
        partition: 'persist:youtube_auth' // Sử dụng partition riêng để không ảnh hưởng app chính
      }
    });

    // Quan trọng: Ghi đè User-Agent để Google cho phép đăng nhập
    const userAgent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
    
    this.authWindow.loadURL('https://accounts.google.com/ServiceLogin?service=youtube', { userAgent });

    return new Promise((resolve) => {
      this.authWindow?.on('closed', () => {
        this.authWindow = null;
        resolve(this.isLoggedIn());
      });

      // Theo dõi điều hướng
      this.authWindow?.webContents.on('did-navigate', async (_event, url) => {
        log.info('[YouTubeAuth] Navigated to:', url);
        
        // Nếu chuyển hướng về youtube.com sau khi đăng nhập
        if (url.includes('youtube.com') && !url.includes('accounts.google.com')) {
          const success = await this.extractAndSaveCookies();
          if (success) {
            log.info('[YouTubeAuth] Login successful, cookies saved.');
            setTimeout(() => {
              this.authWindow?.close();
            }, 2000);
          }
        }
      });
    });
  }

  public async extractAndSaveCookies(): Promise<boolean> {
    try {
      const cookies = await session.fromPartition('persist:youtube_auth').cookies.get({ domain: '.youtube.com' });
      
      if (cookies.length === 0) return false;

      let netscapeContent = '# Netscape HTTP Cookie File\n';
      netscapeContent += '# This file is generated by Melovista. Do not edit.\n\n';

      for (const cookie of cookies) {
        if (!cookie.domain) continue;
        const domain = cookie.domain.startsWith('.') ? cookie.domain : `.${cookie.domain}`;
        const includeSubdomains = 'TRUE';
        const path = cookie.path;
        const secure = cookie.secure ? 'TRUE' : 'FALSE';
        const expiry = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0;
        const name = cookie.name;
        const value = cookie.value;

        netscapeContent += `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expiry}\t${name}\t${value}\n`;
      }

      fs.writeFileSync(this.cookiesPath, netscapeContent, 'utf-8');
      return true;
    } catch (error) {
      log.error('[YouTubeAuth] Failed to extract cookies:', error);
      return false;
    }
  }

  public isLoggedIn(): boolean {
    return fs.existsSync(this.cookiesPath);
  }

  public logout(): void {
    if (fs.existsSync(this.cookiesPath)) {
      fs.unlinkSync(this.cookiesPath);
    }
    session.fromPartition('persist:youtube_auth').clearStorageData();
    log.info('[YouTubeAuth] Logged out and cleared cookies.');
  }
}
